<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="data\plates.mock.json" />
    <Content Remove="data\plates.mock.json" />
    <EmbeddedResource Include="data\plates.mock.json" />
  </ItemGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="9.0.9" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\image\" />
  </ItemGroup>

</Project>